name: donut-lora-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - transformers==4.41.2
      - datasets==2.19.1
      - peft==0.11.1
      - accelerate==0.33.0
      - sentencepiece
      - timm
      - scikit-learn
      - evaluate
      - tensorboard
      - matplotlib
      - pandas
      - pyarrow
      - azure-ai-ml
      - azure-identity
